# Generated by Django 3.0.4 on 2020-03-12 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retail_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Denomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denom_name', models.CharField(max_length=1000)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trig_app.Retailer')),
            ],
        ),
    ]
