# Generated by Django 3.0.8 on 2020-07-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trig_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='retail_addr',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
