# Generated by Django 3.0.8 on 2020-07-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trig_app', '0002_retailer_retail_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='retail_addr',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
